CodeWalker.Core/GameFiles/FileTypes/GtxdFile.cs

GtxdFile: Added BOM check required for some vanilla gtxd.meta

Little fix for some vanilla gtxd.meta

---

CodeWalker.Core/CodeWalker.Core.csproj
CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs
CodeWalker.Core/GameFiles/MetaTypes/Meta.cs
CodeWalker.Core/GameFiles/Resources/Bounds.cs
CodeWalker.Core/Utils/BoundingBoxes.cs
CodeWalker.Core/Utils/Vectors.cs
Project/Panels/EditProjectManifestPanel.cs
Project/Panels/EditYmapGrassPanel.Designer.cs
Project/Panels/EditYmapGrassPanel.cs
Project/Panels/EditYmapGrassPanel.resx
Project/Panels/ProjectExplorerPanel.cs
Project/ProjectForm.Designer.cs
Project/ProjectForm.cs
Rendering/RenderableCache.cs
Rendering/Renderer.cs
Rendering/Shaders/BasicShader.cs
WorldForm.cs

Squashed commits from both revisions. 
Changes to first revision below:
```
1) Grass brush is no longer a control mode, instead it is a boolean.
2) The grass painting function is no longer invoked from the world form, instead the project form invokes the method itself if needed.
3) Removed the ymap component class (unused)
4) Reverted ToString() methods for rage__fwGrassInstanceListDef and rage__fwGrassInstanceListDef__InstanceData structures. Now updating the count everytime it changes.
5) Removed unused vector code.
6) Added method to ArrayOfUShort3 called XYZ() to return u0, u1, and u2 as X,Y, and Z.
7) Removed original boundary structures and now using SharpDX boundary structures. Added BoundingBox extension methods in CodeWalker.Core.Utils file called "BoundingBoxes.cs"
8) Moved all …
```

added grass painting (second revision)

---

Rendering/Shaders/BasicShader.cs
Shaders/BasicPS.hlsl
Shaders/BasicVS_PNCTT.hlsl
Shaders/CodeWalkerShaders.vcxproj
Shaders/CodeWalkerShaders.vcxproj.filters

This mainly enables CodeWalker to render additional textures for vehicles.
The vertex shader is pretty much copy&pasted.
Issues:
- weird rotor blades on top of helis
- needs handling of multiple textures for the same coordinates
- maybe there is a smart alternative for the padding in the shader buffer?

Added vertex shader PNCTT and started implementation of DiffuseSampler2.

---

CodeWalker.Core/GameFiles/RpfFile.cs
CodeWalker.Core/GameFiles/RpfManager.cs

`RpfFile.CopyToModsFolder()` does a standard `System.IO.File.Copy` on the highest-level parent RPF file (the RPF on the file system), to the same location but in the mods folder. Returns the path to the new file, or null if the copy was unsuccessful. Has a string out parameter with a status message. 
Also added/updated some helper functions which are used by the new functionality.

Added method to copy RpfFile to Mods folder

---

CodeWalker.Core/GameFiles/MetaTypes/MetaTypes.cs
CodeWalker.Core/World/Scenarios.cs
Project/Panels/EditScenarioNodePanel.cs
Project/ProjectForm.cs

The game allows to use `ScenarioTypeGroups` in scenario regions, for example, `pier.ymt` and the point at `X:-1854.407 Y:-1213.037 Z:12.5247`.
This pull request adds support for using `ScenarioTypeGroups` with `CScenarioPoint`s and `CScenarioChaningNode`s within the project window. Additionally, in places where the names of scenario type groups would appear, such as when opening a scenario region YMT file, they no longer shows up as hashes since now the names are added to `JenkIndex`.
Main changes:
* Add `ScenarioTypeGroup` class.
* Add `ScenarioTypes.TypeGroups` property to hold the `ScenarioTypeGroup`s loaded from scenarios.meta.
* Add `ScenarioTypeRef` struct that holds either a `ScenarioType` or a `ScenarioTypeGroup` instance.
* Change the type of `MCScenarioPoint.Type` and …

Support for ScenarioTypeGroups in scenario files

---

Utils/GTAFolder.cs

Adds auto-detection of GTA folder from:
- Default/current CodeWalker location
- Steam install
- Retail install
- OpenIV config
Checks registry key for each option above. Returns first match, in that order. Used in GTAFolder setting class.

Auto-detect GTA folder from other programs

---

CodeWalker.Core/GameFiles/Resources/VertexType.cs
Rendering/Shaders/BasicShader.cs
Rendering/Shaders/CableShader.cs
Rendering/Shaders/CloudsShader.cs
Rendering/Shaders/PathShader.cs
Rendering/Shaders/ShadowShader.cs
Rendering/Shaders/SkydomeShader.cs
Rendering/Shaders/TerrainShader.cs
Rendering/Shaders/TreesLodShader.cs
Rendering/Shaders/WaterShader.cs
Rendering/VertexTypes.cs

- VertexComponentType : specifies what each nibble of `VertexDeclarationTypes` is
- VertexDeclarationTypes : the known vertex declaration types used in GTAV
- VertexTypeGTAV : is a helper class which generates the correct layout using `VertexDeclarationTypes`, `VertexType`, `VertexComponentType`
Suggestions:
1. Rename `VertexType` to `VertexDeclarationFlags` and replace enum values with HEX ones
I've rebased my branch to https://github.com/dexyfex/CodeWalker/commit/918ed7fccf7d9e5a0ff2ff8d6768fadfaf828b9d and pushed my edits again to resolve the merge conflict

Dynamic generation of vertex layouts for GTAV vertex types

---

CodeWalker.Core/GameFiles/GameFileCache.cs

This change will simply load the mph4_gtxd.ymt required to correctly load all the textures each drawable of the cayo perico island needs

Cayo Perico: Load mph4_gtxd.ymt

---

CodeWalker.Core/GameFiles/Resources/Bounds.cs

I've scanned all the bounds from ybn, ydr, ydd, yft.
This never happens, and rebuilding resources, apart from padding and different page layout, this is the only "extra" block which gets added over original file once converted to xml and back to rsc

BoundComposite: don't create duplicated ChildrenTransformation blocks

---

CodeWalker/Project/Panels/EditYmapEntityPanel.cs
CodeWalker/Project/Panels/ProjectExplorerPanel.cs
CodeWalker/Project/ProjectForm.Designer.cs
CodeWalker/Project/ProjectForm.cs

Allows for the displaying of entity indexes in the project window to aid LOD setup, this is optional and disabled by default.

Project Form display entity indexes option

---

CodeWalker/World/MapSelection.cs
CodeWalker/WorldForm.cs

- Fix Shift+Click+Drag to copy nodes, without breaking links
- Update node vertex box rendering on drag, including in multi-select mode (previously broken)
- Block drag-copy when multiple path nodes are selected (it doesn't work, only copies the first node)
- Clamp moved nodes to bounds of the area they are in

Fixes for traffic path node editing in world view

---

CodeWalker.Core/World/Water.cs
CodeWalker/Project/ProjectForm.cs
CodeWalker/Rendering/Renderable.cs
CodeWalker/Rendering/Renderer.cs
CodeWalker/World/MapSelection.cs
CodeWalker/World/WorldInfoForm.cs
CodeWalker/WorldForm.Designer.cs
CodeWalker/WorldForm.cs

Screenshot previews: 
**Water Quad selection:**
**Calming Quad selection:**
**Wave Quad selection:**
**Toolbar buttons:**

Add selection modes for water calming and wave quads

---

CodeWalker.Core/GameFiles/Resources/Bounds.cs
CodeWalker.Core/Utils/Vectors.cs

The bounding box calculations for Composite BVH items were incorrect which was causing a lot of issues for certain collisions. For example, prop_gas_tank_01a.yft would not react to certain weapons and the character's head could clip through it in certain spots. 
These calculations have been tested with the original files and are exactly the same in 99.98% of files. In the remaining 0.02% of files, the error is usually only about 0.1 or 0.01 give or take.

Correctly calculate BVH item extents

---

CodeWalker/Forms/YcdForm.cs

Immensely nice QOL feature for synched scenes, as shown below

Order clips in ycd files alphabetically to improve readability

---

CodeWalker.Core/GameFiles/Resources/Drawable.cs
CodeWalker.Core/Utils/FbxConverter.cs

`ShaderGroup.ShaderGroupBlocksSize` (aka `Unknown_30h`) contains the byte size divided by 16 of the ShaderGroup block and its children blocks, when they are packed contiguously in the resource file.
`DrawableBase.DrawableModelsBlocksSize` (aka `Unknown_9Ah`) is similar but with the size of the `DrawableModelsBlock`.
Incorrect values can cause crashes when the model is unloaded.
Discussed here https://discord.com/channels/329138547833700352/329142468102586368/1139264754767122533

Auto-calculate drawables blocks size fields

---

CodeWalker.Core/GameFiles/RpfFile.cs
CodeWalker/ExploreForm.cs

RpfFile:
- Limit RPF entry names to 256 characters because long names can cause the RPFExplorer to freeze when opening its directory.
- Skip RPFs with paths longer that 5000 characters, which are probably an attempt to make CW run out-of-memory.
ExploreForm:
- Use `Path.GetExtension` directly instead of `FileInfo` to prevent `PathTooLongException`s.
- Check for invalid characters in file names to prevent `ArgumentException`s.

Fix crashes due to malicious RPFs

---

CodeWalker.Core/GameFiles/Resources/Clip.cs

These fields contain the phase range (time normalized between 0 and 1) during which the tag is active.

Rename ClipTag.Unknown40/44 to Start/EndPhase

---

CodeWalker.Core/GameFiles/Resources/Clip.cs

Some YCDs have special characters in the clip hash, which causes the XML to be invalid.
missarmenian2.ycd
missfinale_a_ig_2.ycd

Escape ClipBase.Hash when writing XML

---

CodeWalker.Core/GameFiles/FileTypes/YddFile.cs
CodeWalker.Core/GameFiles/Resources/Drawable.cs

When a drawable hash was unknown, it kept the "filename.#dd" name so exporting to XML lost the hash and importing it back created a broken file.
Now if the hash is unknown, the name is set to `hash_1234ABCD`, and XML import checks for `hash_`.

Fix .ydd export/import with unsolved hashes

---

CodeWalker.Core/GameFiles/Resources/Bounds.cs

Seems to be an oversight. While changing the edge index to zero-based.

Offset SetEdgeIndex

---

CodeWalker.Core/GameFiles/FileTypes/YddFile.cs

Some modded .ydd don't follow the .#dd naming (Zmodeler exported peds for example), so don't check that.
The hash check is just in case the drawable contains the solved string but isn't registered in JenkIndex, to avoid HashString from overwriting it to `hash_123`.

Always overwrite drawable name with key from drawable dictionary

---

CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs
CodeWalker.Core/GameFiles/MetaTypes/Archetype.cs

Fixing MLO Instance Data - `groupId`, `floorId`, `defaultEntitySets`*, `numExitPortals`, `MLOInstflags`. 
*There is a bug with **defaultEntitySets** - it is not possible to get and set data items, for example in vanilla files `v_metro_interior_metro_station_3_seoul_milo__3.ymap`, probably incorrect offset, parsing, etc, we get null: [https://github.com/dexyfex/CodeWalker/blob/c45ea837330864c03ca5f355fd38affab85e46c5/CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs#L301](https://github.com/dexyfex/CodeWalker/blob/c45ea837330864c03ca5f355fd38affab85e46c5/CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs#L301)

Fix MLO Instance Data

---

CodeWalker/Project/Panels/GenerateLODLightsPanel.cs

previously, when generating LOD lights the corona intensity would be set even though the source light had its corona disabled by setting the size to 0.

fix(lodlights): only assign corona intensity if size is not 0

---

CodeWalker.Core/World/Camera.cs

Fixing cases: If in 3D view the camera is below the object gizmo, after switching to 2D we cannot control the object gizmo or it is blocked

Fix editing gizmo in 2D Camera

---

CodeWalker/Project/ProjectForm.cs

Set `HasChanged` to false on a new project - Still allows saving of an empty project.
Closing a project now checks against the project `HasChanged` property instead of checking if a project is present.

fix(projectExplorer): Improve Project Logic

---

CodeWalker.Core/GameFiles/GameFileCache.cs
CodeWalker/Project/Panels/GenerateLODLightsPanel.cs

this drastically speeds up the time spent loading assets when generating LOD lights

asynchronously load assets for LOD light generator

---

CodeWalker.Core/GameFiles/MetaTypes/Archetype.cs

• Correct bounding boxes for rotating entities
• Correct rotation around the center of the entity

Fix UpdateBBs for rotated entities
