dexyfex/CodeWalker

- GameFiles/Resources/Bounds.cs
That comment on line 122 is meant to say bit5
MaterialIndex refers to the materials listed in materials.dat
> Edited fields names in Bounds class (BoundingBoxVolume and others)

- GameFiles/FileTypes/GtxdFile.cs
- GameFiles/Resources/Drawable.cs
- Rendering/Renderable.cs
- WorldForm.cs
Some names changed according to Gims Evo and a comment about DrawableModel.Unknown_2Ch
> Edited some names in Drawable.cs 

- CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs
- CodeWalker.Core/GameFiles/Resources/Drawable.cs
- ProjectForm.cs
Just small things to show the the grass batches tree nodes in the project form and other small fixes
> Minus grass related stuffs

- CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs
Ymap: Added saving of GrassInstanceBatches for MetaBuilder, updated BuildInstances (guided by dexy so if it's working thank him, if it's broken blame neos)
> Saving of grass batches for ymaps (fixed)

- CodeWalker.WinForms/TextBoxFix.cs
> TextBoxFix: unused usings removed; ctrl-y & crtl-z features added;

- CodeWalker.Core/GameFiles/Resources/Bounds.cs
- Project/Panels/GenerateNavMeshPanel.cs
@https://github.com/dexyfex/CodeWalker/commit/2716ee84f7a23d0bb5969e94fd7cbc89d4fb6bd0 Added EBoundCompositeFlags and EBoundMaterialFlags 
@https://github.com/dexyfex/CodeWalker/commit/67af15c7679acea53b58aa03ce3aee0a31b41e82 Added properties for RoomId and PedDensity in BoundMaterial_s
> Updated BoundComposite and BoundMaterial_s

- CodeWalker.Core/GameFiles/MetaTypes/Archetype.cs
Support attached objects of portals deletion
> codewalkercore/archetype: portals objects deletion

- CodeWalker.Core/GameFiles/FileTypes/RelFile.cs
Updated Header field names for Dat54RelType.
> Dat54RelType Header Field Names (Update RelFile.cs)

- CodeWalker.Core/GameFiles/FileTypes/RelFile.cs
Main changes:
- Added disassembler/assembler functionality with `Dat10Synth.Disassemble` and `Dat10Synth.Assemble` methods.
- Added list of opcodes in `Dat10Synth.Opcode` enum.
- Renamed `Dat10Synth.OutputsCount1` to `OutputsCount` and `Dat10Synth.OutputsCount2` to `OutputsIndices`, and changed its type to an array of 4 bytes.
> Synth bytecode disassembler/assembler

- CodeWalker.Core/GameFiles/FileTypes/YmapFile.cs
- CodeWalker.Core/GameFiles/MetaTypes/Archetype.cs
Hash generation method was taken from https://github.com/nikez/gtav_audio_occlusion_documentation/blob/master/README.md here
> Changed entity hash generation method to real one used in RAGE

- CodeWalker/Project/MenyooXml.cs
- CodeWalker/Project/ProjectForm.cs
- Added livery support for cargens
- Changed default cargen paint properties to -1 to avoid all-black cars spawning
- Added texture tint variation for props
> Updated Menyoo spooner XML import

- CodeWalker.Core/GameFiles/FileTypes/RelFile.cs
Name the PedR2PVG group of race-aware ped voice groups, as well as various entries for the voice group associated with particular races.
> Race-aware ped voice groups

- CodeWalker.Core/GameFiles/FileTypes/MrfFile.cs
- CodeWalker.Core/GameFiles/GameFile.cs
- CodeWalker.Core/GameFiles/GameFileCache.cs
- CodeWalker/ExploreForm.cs
This PR adds an experimental ability to read and save MRF files.
MRFs are used for complex in-game tasks and minigames.
> MRF files support

- CodeWalker.Core/GameFiles/FileTypes/RelFile.cs
- CodeWalker.Core/World/AudioZones.cs
- CodeWalker/Project/Panels/EditAudioEmitterListPanel.cs
- CodeWalker/Project/Panels/EditAudioEmitterPanel.cs
- CodeWalker/Project/Panels/EditAudioZonePanel.cs
- CodeWalker/Project/Panels/ProjectExplorerPanel.cs
- CodeWalker/Project/ProjectForm.cs
Multiple changes to game.dat151 and sounds.dat54
> Various rel field name changes

- CodeWalker/App.config
- CodeWalker/Properties/Settings.Designer.cs
- CodeWalker/WorldForm.cs
Ability to save:
Time of Day
LOD Lights - on/ff
Region
Clouds
Natural Ambient Light - on/off
Artificial Ambient Light - on/off
Weather
> Add more ability to save more options

- CodeWalker/ExploreForm.cs
Allows you to drop xml files onto the rpf explorer
can be bypassed with shift
> Drag and drop XML files

- CodeWalker/World/WorldSearchForm.Designer.cs
- CodeWalker/World/WorldSearchForm.cs
- CodeWalker/WorldForm.cs
Lets you automatically create markers in the world for all instances of an entity search
> Add set markers button to entity world search

- CodeWalker.Core/GameFiles/FileTypes/CutFile.cs
- CodeWalker.Core/GameFiles/MetaTypes/PsoTypes.cs
Fixes cutscenes failing to load following the metaname update.
> Correct cutscene breaking metaname additions

- CodeWalker.Core/GameFiles/FileTypes/RelFile.cs
- CodeWalker/Project/Panels/EditAudioEmitterPanel.Designer.cs
- CodeWalker/Project/Panels/EditAudioEmitterPanel.cs
- CodeWalker/Project/ProjectForm.cs
dynamix's Patch, 
game's PedVoiceGroup, StartTrackAction, SetMoodAction, Mood, StemMix, AmbientRule, WeaponAudioItem, 
sounds' AutomationSound,
> Audio updates

- CodeWalker/WorldForm.cs
When changing from World View to Model View, populate the Model select box with the selected item's name
Changes made per my feature request
> Set model from selection on changing mode

- CodeWalker.Core/GameFiles/FileTypes/RelFile.cs
- CodeWalker/Project/Panels/EditAudioEmitterPanel.Designer.cs
- CodeWalker/Project/Panels/EditAudioEmitterPanel.cs
- CodeWalker/Project/Panels/EditAudioZonePanel.Designer.cs
- CodeWalker/Project/Panels/EditAudioZonePanel.cs
- CodeWalker/Project/ProjectForm.cs
Updates to the following classes;
Dat22Category
Dat151AmbientRule
Dat151AmbientZone
Dat151DependentAmbience
Dat151Unk124
Dat15Patch
> Audio.rel.xml updates

- CodeWalker/Forms/YvrForm.Designer.cs
- CodeWalker/Forms/YvrForm.cs
- CodeWalker/Forms/YvrForm.resx
- CodeWalker/Forms/YwrForm.Designer.cs
- CodeWalker/Forms/YwrForm.cs
- CodeWalker/Forms/YwrForm.resx
Replaces textbox with listview, old csv format still available through new buttons "Export" and "Copy to clipboard"
> Update ywr/yvr form

- CodeWalker/Utils/Synthesizer.cs
Implemented:
- LERP_BUFFER_2
- OnePole_LPF/HPF
- AWProcess
- AllpassProcess
> Synthesizer progress

- README.md
frontend changes; nothing editorial... yet!
> docs: some README changes

- CodeWalker/Project/Panels/ProjectExplorerPanel.Designer.cs
- CodeWalker/Project/Panels/ProjectExplorerPanel.cs
Added Drag and drop feature for Project Explorer that someone suggested on Discord.
> Drag and drop feature for Project Explorer

- CodeWalker/Forms/ModelLightForm.Designer.cs
- CodeWalker/Forms/ModelLightForm.cs
- CodeWalker/Forms/ModelLightForm.resx
Fixed issue when you click on "Delete Light", the treenode will be deleted
Add a right-click feature (add/remove a light)
old:
new:
> Fixed issue on light editor form

- CodeWalker/Rendering/Renderable.cs
Was discussed before in the CW Discord guild.
> Fix renderable transform multiply

- CodeWalker.Core/GameFiles/Resources/Bounds.cs
First calculates ``VerticesShrunk`` (formerly ``Vertices2``), which is ``Vertices`` shrunken by margin along the normal. Octants are then calculated using these shrunken vertices.
The octants algorithm results in 1:1 octants with all game files when the original Vertices2 is used. However, the auto-calculated Vertices2 are not 1:1 with the original files, so Octants won't be 1:1 with the original files either. This algorithm for calculating shrunken vertices is very close to R*'s implementation though and seems to have no issue in-game.
Thanks to alexguirre, ranstar, and vadzz for doing most of the hard work 😄
> Auto calculate Vertices2 and Octants during XML import

- CodeWalker.Core/GameFiles/Resources/Particle.cs
lmk if i should change or add anything 👌
> tweak(); updated Particle Unknowns to correct names

- CodeWalker/Project/Panels/EditTrainNodePanel.Designer.cs
correct names and add missing 6th train node type
> Update train node types

- CodeWalker/Forms/ModelLightForm.Designer.cs
- CodeWalker/Forms/ModelLightForm.cs
Additional update for merged manually https://github.com/dexyfex/CodeWalker/pull/235
> Additional Update ModelLightForm

- CodeWalker/Rendering/Renderer.cs
Fix visibility of interiors in 2d and orthographic view, disable View Frustum for interiors in these views
> Fix visibility of interiors in 2d and ortho map view

- CodeWalker/Project/ProjectForm.cs
LODDistance is a positive number from 0 to 65535.
Explication
Issue: #273
> Fixes LODDIST issue in Menyoo import

- CodeWalker.Core/GameFiles/FileTypes/YndFile.cs
- CodeWalker.Core/World/Space.cs
- CodeWalker/Project/ProjectForm.cs
previously when attempting to load a lot of ynd files into the project window, it would take a ridiculously long amount of time to finish loading, this is my attempt at trying to improve it.
> tweak(ynd/project): improve YndFile loading time
